### ISSUE TITLE
fix slackbot launching

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#1217]
here's the current crash:

```
(predicators) tslvr@login-3:~/predicators$ tail output.txt 
No local changes to save
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:Learning-and-Intelligent-Systems/predicators
   530eafe6..63402a57  lisdf-merge -> origin/lisdf-merge
Already up to date.
  File "scripts/supercloud/launch.py", line 19
    def _main() -> None:
                ^
SyntaxError: invalid syntax
```

which indicates that it's using the wrong version of Python.

I don't know what recent changes would have caused this.

To reproduce on supercloud:

```
ssh tslvr@login-2 'cd /home/gridsan/tslvr/predicators/ && source /state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/bin/activate predicators && export PYTHONPATH=$PYTHONPATH:/home/gridsan/tslvr/ && export PYTHONHASHSEED=0 && git stash && git checkout master && git pull && rm -f results/* logs/* saved_approaches/* saved_datasets/* && python scripts/supercloud/launch.py --config nightly.yaml --user $USER --on_supercloud'
```

That's copied from `nohup.out`.

I tried to change the python to `/state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/bin/python`, so:

```
ssh tslvr@login-2 'cd /home/gridsan/tslvr/predicators/ && source /state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/bin/activate predicators && export PYTHONPATH=$PYTHONPATH:/home/gridsan/tslvr/ && export PYTHONHASHSEED=0 && git stash && git checkout master && git pull && rm -f results/* logs/* saved_approaches/* saved_datasets/* && /state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/bin/python scripts/supercloud/launch.py --config nightly.yaml --user $USER --on_supercloud'
```

but that led to a scary crash:

```
Traceback (most recent call last):
  File "scripts/supercloud/launch.py", line 16, in <module>
    from scripts.supercloud.submit_supercloud_job import submit_supercloud_job
  File "/home/gridsan/tslvr/predicators/scripts/supercloud/submit_supercloud_job.py", line 7, in <module>
    from predicators import utils
  File "/home/gridsan/tslvr/predicators/predicators/utils.py", line 27, in <module>
    import matplotlib
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/lib/python3.8/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/lib/python3.8/site-packages/matplotlib/rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/lib/python3.8/site-packages/matplotlib/animation.py", line 34, in <module>
    from PIL import Image
  File "/state/partition1/llgrid/pkg/anaconda/anaconda3-2021b/lib/python3.8/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: libwebp.so.7: cannot open shared object file: No such file or directory
```

This all indicates that the anaconda module isn't setting up python correctly like it used to. Most probable cause is something changing on supercloud.

**Comment by tomsilver** [comment]
also since we're using an interactive shell now we can get rid of a bunch of crap:
```ssh tslvr@login-2 -t 'bash -ic "predicate && git stash && git checkout master && git pull && rm -f results/* logs/* saved_approaches/* saved_datasets/* && python scripts/supercloud/launch.py --config nightly.yaml --user $USER --on_supercloud"'```
