### ISSUE TITLE
investigate rare harmlessness failure with oracle option learning in cover multistep

### ISSUE THREAD

**Issue by tomsilver** [Learning-and-Intelligent-Systems/predicators#872]
to reproduce:
```
python src/main.py --env cover_multistep_options --min_perc_data_for_nsrt 1 --segmenter contacts --num_train_tasks 500 --timeout 300 --seed 464 --gnn_num_epochs 10000 --experiment_id cover_multistep_options_oracle_options_500 --approach nsrt_learning --strips_learner oracle
```
example of the error:
```
Learning NSRTs on 498 trajectories...
Traceback (most recent call last):
  File "/home/gridsan/tslvr/predicators/src/main.py", line 367, in <module>
    main()
  File "/home/gridsan/tslvr/predicators/src/main.py", line 109, in main
    _run_pipeline(env, approach, stripped_train_tasks, offline_dataset)
  File "/home/gridsan/tslvr/predicators/src/main.py", line 131, in _run_pipeline
    approach.learn_from_offline_dataset(offline_dataset)
  File "/home/gridsan/tslvr/predicators/src/approaches/nsrt_learning_approach.py", line 50, in learn_from_offline_dataset
    self._learn_nsrts(dataset.trajectories, online_learning_cycle=None)
  File "/home/gridsan/tslvr/predicators/src/approaches/nsrt_learning_approach.py", line 55, in _learn_nsrts
    learn_nsrts_from_data(trajectories,
  File "/home/gridsan/tslvr/predicators/src/nsrt_learning/nsrt_learning_main.py", line 70, in learn_nsrts_from_data
    pnads = learn_strips_operators(
  File "/home/gridsan/tslvr/predicators/src/nsrt_learning/strips_learning/__init__.py", line 46, in learn_strips_operators
    return learner.learn()
  File "/home/gridsan/tslvr/predicators/src/nsrt_learning/strips_learning/base_strips_learner.py", line 46, in learn
    assert self._check_harmlessness(learned_pnads)
AssertionError
```

seems to be rare (3 out of 50 seeds)

**Comment by tomsilver** [comment]
Here's an example:
```
Running harmlessness check...
Harmlessness not preserved for demo!
Initial atoms: {IsBlock(block1:block), IsTarget(target0:target), IsTarget(target1:target), HandEmpty(), IsBlock(block0:block)}
Timestep 1 add effects: {Holding(block1:block, robby:robot)}
Timestep 1 del effects: {HandEmpty()}
Timestep 2 add effects: {Covers(block1:block, target1:target), HandEmpty()}
Timestep 2 del effects: {Holding(block1:block, robby:robot)}
Timestep 3 add effects: {Holding(block1:block, robby:robot)}
Timestep 3 del effects: {HandEmpty()}
Timestep 4 add effects: set()
Timestep 4 del effects: {Covers(block1:block, target1:target)}
Timestep 5 add effects: {Covers(block1:block, target1:target), HandEmpty()}
Timestep 5 del effects: {Holding(block1:block, robby:robot)}
Timestep 6 add effects: {Holding(block0:block, robby:robot)}
Timestep 6 del effects: {HandEmpty()}
Timestep 7 add effects: {Covers(block0:block, target0:target), HandEmpty()}
Timestep 7 del effects: {Holding(block0:block, robby:robot)}
```

with operators:
```
STRIPS-Place:
    Parameters: [?block:block, ?robot:robot, ?target:target]
    Preconditions: [Holding(?block:block, ?robot:robot), IsBlock(?block:block), IsTarget(?target:target)]
    Add Effects: [Covers(?block:block, ?target:target), HandEmpty()]
    Delete Effects: [Holding(?block:block, ?robot:robot)]
    Side Predicates: []
STRIPS-Pick:
    Parameters: [?block:block, ?robot:robot]
    Preconditions: [HandEmpty(), IsBlock(?block:block)]
    Add Effects: [Holding(?block:block, ?robot:robot)]
    Delete Effects: [HandEmpty()]
    Side Predicates: []
```

**Comment by tomsilver** [comment]
Here's a video for that demo:
https://user-images.githubusercontent.com/2816502/168607718-c994c120-0590-40eb-b8f9-71f7d4759468.mp4

**Comment by tomsilver** [comment]
so the problematic case is picking up the block that is already covering the target, which leads to a delete effect for Cover that is not in the oracle operators. ways to resolve:
1. add `--disable_harmlessness_check True` to the option learning script
2. change the oracle operators to allow picking from cover
3. change the environment to disallow picking from a cover

I prefer (1). @ronuchit thoughts?
